
'use server';
/**
 * @fileOverview A redesigned Sora assistant that balances personal portfolio knowledge with general expertise.
 */

import {ai} from '@/ai/genkit';
import {
  PortfolioChatInputSchema,
  type PortfolioChatInput,
  PortfolioChatOutputSchema,
  type PortfolioChatOutput,
} from './portfolio-chat-types';
import {
  AUTHOR_NAME, 
  AUTHOR_EMAIL,
  ABOUT_ME,
  TECH_STACK,
  PROJECTS_DATA,
  EDUCATION_DATA,
  WORK_EXPERIENCE_DATA,
} from '@/lib/data';

const skillsString = TECH_STACK.map(skill => skill.name).join(', ');
const projectsString = PROJECTS_DATA.map(p => {
  return `Project: ${p.title}\nDescription: ${p.description}\nTechnologies: ${p.techStack.map(t => t.name).join(', ')}`;
}).join('\n\n');

const systemInstructions = `
You are Sora, a highly advanced, multilingual AI personal assistant created by Tinkal Kumar.

YOUR IDENTITY & KNOWLEDGE:
- You are Tinkal's representative. You know everything about his career, projects, and skills based on the provided context.
- You are ALSO a world-class general-purpose AI. You can answer ANY question on ANY topic (coding, history, science, life advice, translations) using your vast internal training data.

BEHAVIOR:
1. **Multilingual Mastery**: Fluently detect the user's language. If they ask in Hindi, answer in Hindi. If they ask in Hinglish, answer in Hinglish. Be natural and helpful.
2. **Contextual Aware**: If a question is about Tinkal, use the context below. If it's a general question, answer as an expert AI.
3. **Friendly & Proactive**: Be encouraging and expert. When providing code, ensure it is clean and explained.

TINKAL KUMAR'S CONTEXT:
Name: ${AUTHOR_NAME}
Bio: ${ABOUT_ME.summary}
Skills: ${skillsString}
Location: ${ABOUT_ME.location}
Projects:
${projectsString}
Work/Education: ${WORK_EXPERIENCE_DATA.map(w => w.title).join(', ')} / ${EDUCATION_DATA.map(e => e.degree).join(', ')}

Current Info: Year: {{{currentYear}}}, Time in India: {{{currentDateTimeIndia}}}

OUTPUT FORMAT:
Provide your response, then exactly 4 brief follow-up suggestions (max 6 words each).
`;

const chatPrompt = ai.definePrompt({
  name: 'portfolioChatSoraPrompt', 
  input: {schema: PortfolioChatInputSchema},
  output: {schema: PortfolioChatOutputSchema},
  prompt: `${systemInstructions}\n\nUser Question: {{userInput}}`,
});

const portfolioChatFlowInternal = ai.defineFlow(
  {
    name: 'portfolioChatFlowInternalSora', 
    inputSchema: PortfolioChatInputSchema,
    outputSchema: PortfolioChatOutputSchema,
  },
  async (input) => {
    try {
      const llmResponse = await chatPrompt(input); 
      const output = llmResponse.output;

      if (!output) throw new Error("No output generated by AI");

      console.log(`[Sora] User: ${input.userInput} | Response: ${output.response.substring(0, 50)}...`);

      return {
          response: output.response,
          suggestedFollowUps: output.suggestedFollowUps?.slice(0, 4) || []
      };
    } catch (error: any) {
        console.error("Sora Execution Error:", error);
        
        let userFriendlyError = "I'm having a brief moment of reflection. Please try again in a few seconds!";
        
        if (error.message?.includes("429")) {
          userFriendlyError = "My AI brain is a bit busy (quota reached). Can we try again in a minute?";
        } else if (error.message?.includes("404")) {
          userFriendlyError = "I'm having trouble connecting to my knowledge base (404). My team is checking the configuration!";
        }

        return {
            response: userFriendlyError,
            suggestedFollowUps: ["Tell me about Tinkal?", "What are his skills?", "Show me projects", "How to contact him?"]
        };
    }
  }
);

export async function getPortfolioChatResponse(rawInput: Omit<PortfolioChatInput, 'currentYear' | 'currentDateTimeIndia'>): Promise<PortfolioChatOutput> {
  const now = new Date();
  return portfolioChatFlowInternal({
    ...rawInput,
    currentYear: now.getFullYear(),
    currentDateTimeIndia: now.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
  });
}
